name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci --production

    - name: Build application
      run: |
        echo "Application ready for deployment"

    - name: Create deployment package
      run: zip -r deploy.zip . -x "*.git*" "node_modules/*" "*.md" "tests/*"

    - name: Decode publish profile
      run: echo "${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BASE64 }}" | base64 -d > publish-profile.xml

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'salesforce-dashboard-linux'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: deploy.zip