name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci --production

    - name: Create deployment package
      run: |
        # Remove unnecessary files for production
        rm -rf .git
        rm -rf .github
        rm -rf test-results
        rm -f .gitignore

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'salesforce-dashboard-linux'
        slot-name: 'production'
        resource-group: 'rg-salesforce-dashboard'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '.'

    - name: Test deployment
      run: |
        sleep 30
        curl -f https://salesforce-dashboard-linux.azurewebsites.net/api/division-summary || exit 1